Repository redtaped/ez-startup, pull requests merged in 2023-11, with the labels that each got.

#4 maint: add gitignore file
  .gitignore
Labels: ci/cd

#8 feat: add jw library startup code
  src/Console/Program.cs
Labels: enhancement

#10 maint: added classes and changed Console namespace to App
  src/App/App.csproj
  src/App/App.sln
  src/App/IEzStartup.cs
  src/App/Program.cs
  src/App/WindowsEzStartup.cs
  src/Console/Program.cs
Labels: enhancement

#12 chore: redesign to support DI
  ez-startup.sln
  src/App/App.csproj
  src/App/App.sln
  src/App/IEzStartup.cs
  src/App/Program.cs
  src/App/WindowsEzStartup.cs
  src/Common/Common.csproj
  src/Common/IEzStartup.cs
  src/Logic/Logic.csproj
  src/Logic/ServiceCollectionExtensions.cs
  src/Logic/WindowsEzStartup.cs
Labels: enhancement

#13 chore: fix sln file
  .vscode/tasks.json
  ez-startup.sln
Labels: bug

#15 feature: make loader which runs from config
  .DS_Store
  .vscode/launch.json
  .vscode/tasks.json
  ez-startup.sln
  src/.DS_Store
  src/App/.DS_Store
  src/App/App.csproj
  src/App/Program.cs
  src/App/appsettings.json
  src/App/appsettings.osx-arm64.json
  src/App/appsettings.win-x64.json
  src/Common/Common.csproj
  src/Common/Models/ApplicationInfo.cs
  src/Common/Models/Configuration.cs
  src/Logic/AppLauncher.cs
  src/Logic/ILaunchApps.cs
  src/Logic/ILoader.cs
  src/Logic/Loader.cs
  src/Logic/Logic.csproj
  src/Logic/ServiceCollectionExtensions.cs
Labels: enhancement
